import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type RawExerciseRecord = {
  id: string;
  name: string;
  force: string | null;
  level: string | null;
  mechanic: string | null;
  equipment: string | null;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  instructions: string[];
  category: string | null;
  images: string[];
};

function toSlug(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function escapeSql(value: string | null) {
  if (value == null) {
    return "null";
  }

  return `'${value.replace(/'/g, "''")}'`;
}

function escapeJson(value: unknown) {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

async function main() {
  const rawPath = path.join(
    process.cwd(),
    "src",
    "lib",
    "data",
    "exercise-catalog.raw.json",
  );
  const outputPath = path.join(process.cwd(), "supabase", "seed.sql");
  const rawContent = await readFile(rawPath, "utf8");
  const exercises = JSON.parse(rawContent) as RawExerciseRecord[];

  const statements: string[] = [
    "-- Generated by scripts/generate-exercise-seed.ts",
    "begin;",
    "delete from exercise_muscles where exercise_id in (select id from exercises where source = 'built-in');",
    "delete from exercise_aliases where exercise_id in (select id from exercises where source = 'built-in');",
    "delete from exercises where source = 'built-in';",
  ];

  exercises.forEach((exercise) => {
    const slug = toSlug(exercise.id);
    const anatomyLabel = exercise.primaryMuscles[0] ?? "full body";

    statements.push(`
insert into exercises (
  slug,
  source,
  name,
  force,
  level,
  mechanic,
  equipment,
  category,
  instructions,
  anatomy_label,
  archived
) values (
  ${escapeSql(slug)},
  'built-in',
  ${escapeSql(exercise.name)},
  ${escapeSql(exercise.force)},
  ${escapeSql(exercise.level)},
  ${escapeSql(exercise.mechanic)},
  ${escapeSql(exercise.equipment)},
  ${escapeSql(exercise.category)},
  ${escapeJson(exercise.instructions ?? [])},
  ${escapeSql(anatomyLabel)},
  false
)
on conflict (slug) do update set
  name = excluded.name,
  force = excluded.force,
  level = excluded.level,
  mechanic = excluded.mechanic,
  equipment = excluded.equipment,
  category = excluded.category,
  instructions = excluded.instructions,
  anatomy_label = excluded.anatomy_label,
  archived = excluded.archived;`.trim());

    statements.push(`
insert into exercise_aliases (exercise_id, alias)
select id, ${escapeSql(exercise.name.toLowerCase())}
from exercises
where slug = ${escapeSql(slug)}
on conflict (exercise_id, alias) do nothing;`.trim());

    [...(exercise.primaryMuscles ?? [])].forEach((muscle) => {
      statements.push(`
insert into exercise_muscles (exercise_id, muscle, is_primary)
select id, ${escapeSql(muscle)}, true
from exercises
where slug = ${escapeSql(slug)}
on conflict (exercise_id, muscle, is_primary) do nothing;`.trim());
    });

    [...(exercise.secondaryMuscles ?? [])].forEach((muscle) => {
      statements.push(`
insert into exercise_muscles (exercise_id, muscle, is_primary)
select id, ${escapeSql(muscle)}, false
from exercises
where slug = ${escapeSql(slug)}
on conflict (exercise_id, muscle, is_primary) do nothing;`.trim());
    });
  });

  statements.push("commit;");

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, `${statements.join("\n\n")}\n`, "utf8");
  console.log(`Generated Supabase seed file at ${outputPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
